[build]
  publish = "dist"
  command = "npm ci && ./scripts/bundle-ffmpeg.sh && npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # Default timeout for all functions
  "*" = { timeout = 60 }

# render-frames function needs @sparticuz/chromium for server-side rendering + gifuct-js for GIF processing
[functions."render-frames"]
  timeout = 60
  external_node_modules = ["@sparticuz/chromium", "gifuct-js"]
  included_files = [
    "node_modules/@sparticuz/chromium/bin/**",
    "node_modules/gifuct-js/lib/**"
  ]

# make-webm function already has bundled FFmpeg binary
[functions."make-webm"]
  timeout = 60

[functions.environment]
  # Pin to Node.js 22 runtime to match build environment
  NODE_VERSION = "22"
  AWS_LAMBDA_JS_RUNTIME = "nodejs22.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-Telegram-InitData"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables for development
[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.production.environment]
  NODE_ENV = "production"
