[build]
  publish = "dist"
  command = "npm ci && ./scripts/bundle-ffmpeg.sh && npm run build"
  functions = "netlify/functions"

# Add Netlify Chromium plugin for server-side rendering
[[plugins]]
package = "netlify-plugin-chromium"

[functions]
  node_bundler = "esbuild"
  # Default timeout for all functions
  "*" = { timeout = 60 }

# render-frames function needs Chromium for server-side rendering
[functions."render-frames"]
  timeout = 60
  external_node_modules = ["chromium"]
  included_files = ["node_modules/chromium/lib/chromium/**"]

# make-webm function already has bundled FFmpeg binary
[functions."make-webm"]
  timeout = 60

[functions.environment]
  # Upgrade to Node.js 20 for better Puppeteer support
  NODE_VERSION = "20"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-Telegram-InitData"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables for development
[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.production.environment]
  NODE_ENV = "production"
