[build]
  publish = "dist"
  command = "npm ci && ./scripts/bundle-ffmpeg.sh && npm run build"
  functions = "netlify/functions"

# Add Netlify Chromium plugin for server-side rendering
[[plugins]]
package = "netlify-plugin-chromium"

[functions]
  node_bundler = "esbuild"
  # Increase timeout for video processing and server-side rendering
  "*" = { timeout = 60 }
  # Increase size limit for functions with bundled FFmpeg binary
  "make-webm" = { timeout = 60, size = 100000000 }

[functions.environment]
  # Upgrade to Node.js 20 for better Puppeteer support
  NODE_VERSION = "20"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"
  # Ensure Chrome path is available at runtime
  CHROME_PATH = "/opt/chromium/chrome"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-Telegram-InitData"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables for development
[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.production.environment]
  NODE_ENV = "production"
